/*
 * Gilfoyle server
 *
 * Video streaming server backed by decentralized filesystem.
 *
 * API version: 0.1-beta
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type EntVideo struct {
	CreatedAt string `json:"created_at,omitempty"`
	Id string `json:"id,omitempty"`
	Status string `json:"status,omitempty"`
	Title string `json:"title,omitempty"`
	UpdatedAt string `json:"updated_at,omitempty"`
}
