/*
 * Gilfoyle server
 *
 * Media streaming server backed by decentralized filesystem.
 *
 * API version: 0.1-beta
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type InlineResponse2001 struct {
	Data *EntMedia `json:"data,omitempty"`
	HttputilsDataResponse *HttputilsDataResponse `json:"httputils.DataResponse,omitempty"`
}
