/*
 * Gilfoyle server
 *
 * Video streaming server backed by decentralized filesystem.
 *
 * API version: 0.1-beta
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type HttputilsErrorResponse struct {
	Code int32 `json:"code,omitempty"`
	Message string `json:"message,omitempty"`
}
