/*
 * Gilfoyle server
 *
 * Video streaming server backed by decentralized filesystem.
 *
 * API version: 0.1-beta
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// InlineResponse200 struct for InlineResponse200
type InlineResponse200 struct {
	Data []EntVideo `json:"data,omitempty"`
	HttputilsDataResponse HttputilsDataResponse `json:"httputils.DataResponse,omitempty"`
}
