/*
 * Gilfoyle server
 *
 * Video streaming server backed by decentralized filesystem.
 *
 * API version: 0.1-beta
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// HttputilsErrorResponse struct for HttputilsErrorResponse
type HttputilsErrorResponse struct {
	Code int32 `json:"code,omitempty"`
	Message string `json:"message,omitempty"`
}
