/*
 * Gilfoyle server
 *
 * Video streaming server backed by decentralized filesystem.
 *
 * API version: 0.1-beta
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// HttputilsDataResponse struct for HttputilsDataResponse
type HttputilsDataResponse struct {
	Code int32 `json:"code,omitempty"`
	Data map[string]interface{} `json:"data,omitempty"`
}
