/*
 * Gilfoyle server
 *
 * Cloud-native media hosting & streaming server for businesses.
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type EntMedia struct {
	CreatedAt string `json:"created_at,omitempty"`
	Id string `json:"id,omitempty"`
	Status string `json:"status,omitempty"`
	Title string `json:"title,omitempty"`
	UpdatedAt string `json:"updated_at,omitempty"`
}
