/*
 * Gilfoyle server
 *
 * Cloud-native media hosting & streaming server for businesses.
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type EntMediaFile struct {
	// CreatedAt holds the value of the \"created_at\" field.
	CreatedAt string `json:"created_at,omitempty"`
	// DurationSeconds holds the value of the \"duration_seconds\" field.
	DurationSeconds float32 `json:"duration_seconds,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph. The values are being populated by the MediaFileQuery when eager-loading is set.
	Edges *EntMediaFileEdges `json:"edges,omitempty"`
	// Format holds the value of the \"format\" field.
	Format string `json:"format,omitempty"`
	// Framerate holds the value of the \"framerate\" field.
	Framerate int32 `json:"framerate,omitempty"`
	// ID of the ent.
	Id string `json:"id,omitempty"`
	// MediaType holds the value of the \"media_type\" field.
	MediaType string `json:"media_type,omitempty"`
	// RenditionName holds the value of the \"rendition_name\" field.
	RenditionName string `json:"rendition_name,omitempty"`
	// ResolutionHeight holds the value of the \"resolution_height\" field.
	ResolutionHeight int32 `json:"resolution_height,omitempty"`
	// ResolutionWidth holds the value of the \"resolution_width\" field.
	ResolutionWidth int32 `json:"resolution_width,omitempty"`
	// TargetBandwidth holds the value of the \"target_bandwidth\" field.
	TargetBandwidth int32 `json:"target_bandwidth,omitempty"`
	// UpdatedAt holds the value of the \"updated_at\" field.
	UpdatedAt string `json:"updated_at,omitempty"`
	// VideoBitrate holds the value of the \"video_bitrate\" field.
	VideoBitrate int32 `json:"video_bitrate,omitempty"`
}
