/*
 * Gilfoyle server
 *
 * Cloud-native media hosting & streaming server for businesses.
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type ApiFileFormat struct {
	BitRate string `json:"bit_rate,omitempty"`
	Duration string `json:"duration,omitempty"`
	Filename string `json:"filename,omitempty"`
	FormatLongName string `json:"format_long_name,omitempty"`
	FormatName string `json:"format_name,omitempty"`
	NbPrograms int32 `json:"nb_programs,omitempty"`
	NbStreams int32 `json:"nb_streams,omitempty"`
	ProbeScore int32 `json:"probe_score,omitempty"`
	Size string `json:"size,omitempty"`
	StartTime string `json:"start_time,omitempty"`
}
