/*
 * Gilfoyle server
 *
 * Video streaming server backed by decentralized filesystem.
 *
 * API version: 0.1-beta
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// InlineResponse2001 struct for InlineResponse2001
type InlineResponse2001 struct {
	Data EntVideo `json:"data,omitempty"`
	HttputilsDataResponse HttputilsDataResponse `json:"httputils.DataResponse,omitempty"`
}
