/*
 * Gilfoyle server
 *
 * Cloud-native media hosting & streaming server for businesses.
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type DialectDriver struct {
}
