/*
 * Gilfoyle server
 *
 * Media streaming server backed by decentralized filesystem.
 *
 * API version: 0.1-beta
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type ApiUpdateMedia struct {
	Title string `json:"title"`
}
