/*
 * Gilfoyle server
 *
 * Cloud-native media hosting & streaming server for businesses.
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type ApiMediasMetadata struct {
	Limit int32 `json:"limit,omitempty"`
	Offset int32 `json:"offset,omitempty"`
	Total int32 `json:"total,omitempty"`
}
