/*
 * Gilfoyle server
 *
 * Media streaming server backed by decentralized filesystem.
 *
 * API version: 0.1-beta
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type HttputilsDataResponse struct {
	Code int32 `json:"code,omitempty"`
	Data *interface{} `json:"data,omitempty"`
}
