/*
 * Gilfoyle server
 *
 * Cloud-native media hosting & streaming server for businesses.
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type EntMediaFileEdges struct {
	// Media holds the value of the media edge.
	Media *EntMedia `json:"media,omitempty"`
}
