/*
 * Gilfoyle server
 *
 * Video streaming server backed by decentralized filesystem.
 *
 * API version: 0.1-beta
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// EntVideo struct for EntVideo
type EntVideo struct {
	CreatedAt string `json:"created_at,omitempty"`
	Id string `json:"id,omitempty"`
	Status string `json:"status,omitempty"`
	Title string `json:"title,omitempty"`
	UpdatedAt string `json:"updated_at,omitempty"`
}
