/*
 * Gilfoyle server
 *
 * Cloud-native media hosting & streaming server for businesses.
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type InlineResponse2002 struct {
	Data *EntMedia `json:"data,omitempty"`
	HttputilsDataResponse *HttputilsDataResponse `json:"httputils.DataResponse,omitempty"`
}
