/*
 * Gilfoyle server
 *
 * Cloud-native media hosting & streaming server for businesses.
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type ApiHealthCheckResponse struct {
	Commit string `json:"commit,omitempty"`
	Tag string `json:"tag,omitempty"`
}
