name: Codegen

on:
  schedule:
    #- cron: "0 0 * * *"
    - cron: "15 * * * *"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Generate client
      run: |
          git remote set-url origin https://dreamvo:${{ secrets.GITHUB_TOKEN }}@github.com/dreamvo/go-gilfoyle.git
          git config --global user.name dreamvo
          git config --global user.email dreamvo@users.noreply.github.com
          docker run --rm -v ${PWD}:/app swaggerapi/swagger-codegen-cli generate -i https://raw.githubusercontent.com/dreamvo/gilfoyle/master/api/docs/swagger.json -l go -o /app
          if [[ -z $(git status -s) ]]
          then
            echo "tree is clean, exiting"
            exit 0
          else
            git add . && git commit -m "swagger: run code generation"
            git pull origin master --rebase
            git push origin master
          fi
