name: Codegen

on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      ORGANIZATION: dreamvo
      REPOSITORY: go-gilfoyle
      CODEGEN_LANG: go
    steps:

    - name: Check out code from the repository
      uses: actions/checkout@v2

    - name: Generate client
      run: |
          git config --global user.name "$GITHUB_ACTOR"
          git config --global user.email "$GITHUB_ACTOR@users.noreply.github.com"
          docker run --rm -v ${PWD}:/app swaggerapi/swagger-codegen-cli generate -i https://raw.githubusercontent.com/dreamvo/gilfoyle/master/api/docs/swagger.json -l $CODEGEN_LANG -o /app --git-user-id "$ORGANIZATION" --git-repo-id $REPOSITORY
          if [[ -z $(git status -s) ]]
          then
            echo "tree is clean, exiting"
            exit 0
          else
            git add . && git commit -m "swagger: run code generation"
            git pull origin master --rebase
            git push origin master
          fi
